export { default as Dummy1 } from "@/assets/dummy/1.png";
export { default as Dummy2 } from "@/assets/dummy/2.png";
export { default as ArrowRight } from "@/assets/icons/arrow-right.svg";
export { default as TopArrowIcon } from "@/assets/icons/top-arrow.svg";
export { default as Building } from "@/assets/images/building.svg";
export { default as FooterBg } from "@/assets/images/footer-bg.svg";
export { default as Life } from "@/assets/images/life.png";
export { default as LogoBlack } from "@/assets/images/logo-black.svg";
export { default as Logo } from "@/assets/images/logo-white.svg";
export { default as SponsorsDummy1 } from "@/assets/dummy/sponsors-dummy-1.png";
 export { default as SponsorsDummy2 } from "@/assets/dummy/sponsors-dummy-2.png";
 export { default as SponsorsDummy3 } from "@/assets/dummy/sponsors-dummy-3.png";
 export {default as SponsorsDummy4} from "@/assets/dummy/sponsors-dummy-4.png";
 export {default as SponsorsDummy5} from "@/assets/dummy/sponsors-dummy-5.png";
 export {default as SponsorsDummy6} from "@/assets/dummy/sponsors-dummy-6.png";
