export const dynamic = "force-dynamic";

import type { Metadata } from "next";
import { Mulish, Urbanist } from "next/font/google";
import WebFooter from "@/components/layouts/WebFooter";
import WebHeader from "@/components/layouts/WebHeader";
import "./globals.css";

const mulish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"],
});

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${mulish.variable} ${urbanist.variable} antialiased flex flex-col min-h-screen`}
      >
        <WebHeader />
        <main className="flex-1 w-full">{children}</main>
        <WebFooter />
      </body>
    </html>
  );
}
